# Site settings
name: Comnets
email: email
url: url
description: "A blog and a portfolio"
author: "Comnets"
title: "IoT - connect them all"
permalink: pretty
# baseurl: 

# social
github:
  username: ComNets-Bremen

twitter:
  username: ComNetsBremen