# Site settings
name: Comnets
email: email
url: url
description: "A blog and a portfolio"
author: "Comnets"
title: "IoT-Lab"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: ComNets-Bremen

twitter:
  username: ComNetsBremen